server:
  port: 8085
  error:
    include-message: always
    include-binding-errors: always
spring:
  data:
    web:
      pageable:
        default-page-size: 3
  datasource:
    url: jdbc:postgresql://localhost:5432/academy_db
    username: academy
    password: 2easy2forget
    driver-class-name: org.postgresql.Driver
  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always

