server:
  error:
    include-message: never # Desabilita mensagens detalhadas de erro para segurança
    include-binding-errors: never

spring:
  data:
    web:
      pageable:
        default-page-size: 10 # Pode aumentar o tamanho da página em produção, se necessário

  datasource:
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE} # Variável de ambiente no Railway para o URL do banco de dados
    username: ${PG_USER} # Nome do usuário para o banco, usando variável de ambiente
    password: ${PG_PASSWORD} # Senha do banco, usando variável de ambiente
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false # Desabilitar em produção para evitar exposição de consultas SQL
    hibernate:
      ddl-auto: update # Usar "update" em vez de "create-drop" para manter dados em produção

  sql:
    init:
      mode: never # Evita reinicialização do banco ao iniciar a aplicação em produção